# Generated by Django 6.0.2 on 2026-06-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
